### ISSUE TITLE
Dailies are outdated for EU

### ISSUE THREAD

**Issue by kasoki** [kasoki/LoginWars2#8]
The current daily API only provides dailies correctly for NA players, ArenaNet is changing that soon-ish which will break the endpoint.

**Comment by kasoki** [comment]
Status update: According to ArenaNet this won't be fixed until the Dec. 1 patch. Maybe I should disable dailies for now and readd this later? But then again only EU players are affected...

**Comment by KTkabo0m** [comment]
Dailies are not in sync in NA as well. 
 For example today LoginWars2 says the PvE dailies are: 
- Maguuma Jungle Forager
- Mystic Forger
- Queensdale Events
- Great Jungle Wurm

But they are: 
- Daily Maguuma Jungle Lumberer
- Daily Maguuma Vista Viewer
- Daily Kessex Hills Event Completer
![loginwars2launcherlistsdailieswrong](https://cloud.githubusercontent.com/assets/15949416/11313277/a10c26ca-8fa9-11e5-83a7-9b6f45c647fe.jpg)

- Daily Shadow Behemoth

**Comment by KTkabo0m** [comment]
Not sure if this is of use or not but I have noticed that this site is correct: http://timer.silversunshine.net/  What code are they using?

**Comment by kasoki** [comment]
```
Anyway, the backend fixes are in as of an hour ago, so I should have the endpoint spitting out the correct data sometime this week.
```

Guess that resolves the issue ;).
